### ISSUE TITLE
ImportError: cannot import name 'AgentID' from 'pettingzoo.utils.env' & cannot import simple_spread_v3 from pettingzoo.mpe

### ISSUE THREAD

**Issue by lhw0719** [ffelten/MASAC#3]
Hello, your code is amazing, but i still encounter a few bugs. As you said in README.md, your code is is based on the SAC implementation from cleanRL repo, so i create the same virtual environment as cleanRL v1.0.0, but i still encounter the two bugs above.  Can you please give me the detailed requirements.txt for that code to help me fix these bugs? My current requirements.txt (which is the same as cleanRL v1.0.0) is in the attached file. My python version is 3.8.20, pettingzoo version is 1.18.1. Looking forward to your reply. Thank you.
[requirements.txt](https://github.com/user-attachments/files/17838893/requirements.txt)

**Comment by ffelten** [comment]
Hey,

Thank you for the kind words.

I haven't really played with this for over a year now. But if I remember well, the poetry.lock file contains what you're looking for :)

**Comment by lhw0719** [comment]
Thank you very much for your answer. I realised that this was a stupid question because I didn't read the README.md carefully.I didn't know about the tool poetry before and had been using pip and conda for the installation of the virtual environment, which led to the error. Now the code is working fine.
